version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:14.5
    environment:
      POSTGRES_DB: "stepdb"
      POSTGRES_USER: "stepuser"
      POSTGRES_PASSWORD: "pgpwd4step"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stepuser -d stepdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  postgres_exporter:
    container_name: exporter_container
    image: prometheuscommunity/postgres-exporter:v0.10.0
    environment:
      DATA_SOURCE_URI: "postgres:5432/stepdb?sslmode=disable"
      DATA_SOURCE_USER: "stepuser"
      DATA_SOURCE_PASS: "pgpwd4step"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
    volumes:
      - ./queries.yaml:/etc/postgres_exporter/queries.yaml:ro
    ports:
      - "9187:9187"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 500M
    networks:
      - postgres
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_log:/var/log/rabbitmq/
    networks:
        - rabbitmq_net

volumes:
    rabbitmq_data:
    rabbitmq_log:

networks:
  postgres:
    driver: bridge
  rabbitmq_net:
    driver: bridge
